//! CSS Grid Layout (css-grid-1), implemented FROM THE SPEC TEXT (read
//! 2026-07-05; section names below are the spec's own): the track model
//! (§7.2 incl. repeat()/auto-fill/auto-fit), line-based placement and the
//! §8.5 auto-placement algorithm, named areas (§7.3), and the §11 track
//! sizing algorithm — initialize (§11.4), resolve intrinsic sizes with the
//! infinitely-growable flag (§11.5), maximize (§11.6), expand flexible
//! tracks via find-the-size-of-an-fr (§11.7), and stretch auto tracks
//! (§11.8).
//!
//! The old engine's TrackSpec GRAMMAR survives through its proven
//! tokenizer (`split_track_tokens` — paren-aware, `[line-name]`-dropping);
//! the sizing functions themselves are rebuilt on `Len` so everything
//! resolves in px space against real used widths, never pre-quantized
//! cells. Named LINES are dropped by that tokenizer (documented — named
//! AREAS are supported and cover the common authoring pattern); subgrid
//! and baseline shims are out of scope for this phase.

use std::ops::Range;

use crate::dom::NodeId;
use crate::layout::{NO_NODE, Units, split_track_tokens};

use super::flex::{Justify, justify_offsets};
use super::flow::{Flow, Frag};
use super::intrinsic::IMode;
use super::style::InlineStyle;
use super::style::{BOTTOM, LEFT, RIGHT, TOP};
use super::tree::BoxNode;
use super::value::{Len, Vp, split_args};

/// One track sizing function pair per §11.2: `minmax()` splits, `<flex>`
/// and `fit-content()` take an `auto` minimum, plain values serve as both.
#[derive(Clone, Debug)]
pub(crate) struct TrackSize {
    min: TrackFn,
    max: TrackFn,
}

#[derive(Clone, Debug, PartialEq)]
pub(crate) enum TrackFn {
    Fixed(Len),
    Auto,
    MinContent,
    MaxContent,
    Fr(f32),
    FitContent(Len),
}

impl TrackFn {
    fn definite(&self, basis: Option<f32>) -> Option<f32> {
        match self {
            TrackFn::Fixed(l) => l.resolve(basis).map(|v| v.max(0.0)),
            _ => None,
        }
    }

    fn is_intrinsic(&self) -> bool {
        matches!(
            self,
            TrackFn::Auto | TrackFn::MinContent | TrackFn::MaxContent | TrackFn::FitContent(_)
        )
    }
}

/// One track mid-§11: sizing functions plus base size / growth limit.
#[derive(Clone, Debug)]
pub(crate) struct Track {
    pub size: TrackSize,
    pub base: f32,
    limit: f32,
    /// §11.5's "infinitely growable" flag (the Peter Salas case).
    inf_growable: bool,
    /// Generated by an auto-FIT repetition: collapses when no item spans it.
    collapsible: bool,
    pub collapsed: bool,
}

impl Track {
    fn new(size: TrackSize, collapsible: bool) -> Track {
        Track {
            size,
            base: 0.0,
            limit: f32::INFINITY,
            inf_growable: false,
            collapsible,
            collapsed: false,
        }
    }
}

/// Parse one track-size token into its §11.2 (min, max) pair.
fn parse_track_size(tok: &str, u: Units, vp: Vp) -> Option<TrackSize> {
    let t = tok.trim();
    let lower = t.to_ascii_lowercase();
    let simple = |s: &str| -> Option<TrackFn> {
        match s.trim().to_ascii_lowercase().as_str() {
            "auto" => Some(TrackFn::Auto),
            "min-content" => Some(TrackFn::MinContent),
            "max-content" => Some(TrackFn::MaxContent),
            other => {
                if let Some(fr) = other.strip_suffix("fr") {
                    return fr
                        .trim()
                        .parse::<f32>()
                        .ok()
                        .filter(|f| *f >= 0.0)
                        .map(TrackFn::Fr);
                }
                Len::parse(s, u, vp).map(TrackFn::Fixed)
            }
        }
    };
    if let Some(inner) = lower
        .starts_with("minmax(")
        .then(|| t.get(7..t.len().saturating_sub(1)))
        .flatten()
        .filter(|_| lower.ends_with(')'))
    {
        let args = split_args(inner);
        if args.len() != 2 {
            return None;
        }
        let min = match simple(args[0])? {
            // A <flex> minimum is invalid grammar; §11.2 fallback is auto.
            TrackFn::Fr(_) => return None,
            f => f,
        };
        let max = simple(args[1])?;
        return Some(TrackSize { min, max });
    }
    if let Some(inner) = lower
        .starts_with("fit-content(")
        .then(|| t.get(12..t.len().saturating_sub(1)))
        .flatten()
        .filter(|_| lower.ends_with(')'))
    {
        let l = Len::parse(inner, u, vp)?;
        return Some(TrackSize {
            min: TrackFn::Auto,
            max: TrackFn::FitContent(l),
        });
    }
    match simple(t)? {
        TrackFn::Fr(f) => Some(TrackSize {
            // §11.2: a <flex> track's min sizing function is auto.
            min: TrackFn::Auto,
            max: TrackFn::Fr(f),
        }),
        f => Some(TrackSize {
            min: f.clone(),
            max: f,
        }),
    }
}

/// A parsed template segment: a plain track, or one auto-repetition group
/// (whose count resolves against the available space, §7.2.3.2).
enum Seg {
    One(TrackSize),
    AutoRepeat { reps: Vec<TrackSize>, fit: bool },
}

/// Parse a `grid-template-columns`/`-rows` value into tracks, expanding
/// `repeat()`. `None` = no usable template (`none`, empty, or unparseable —
/// the whole declaration is dropped, matching the invalid-declaration rule).
fn parse_template(
    value: &str,
    u: Units,
    vp: Vp,
    avail: Option<f32>,
    gap: f32,
) -> Option<Vec<Track>> {
    let v = value.trim();
    if v.is_empty() || v.eq_ignore_ascii_case("none") {
        return None;
    }
    let mut segs: Vec<Seg> = Vec::new();
    for tok in split_track_tokens(v) {
        let lower = tok.to_ascii_lowercase();
        if lower.starts_with("repeat(") && lower.ends_with(')') {
            let inner = &tok[7..tok.len() - 1];
            let (count, list) = inner.split_once(',')?;
            let sizes: Vec<TrackSize> = split_track_tokens(list)
                .iter()
                .map(|t| parse_track_size(t, u, vp))
                .collect::<Option<_>>()?;
            if sizes.is_empty() {
                return None;
            }
            match count.trim().to_ascii_lowercase().as_str() {
                "auto-fill" => segs.push(Seg::AutoRepeat {
                    reps: sizes,
                    fit: false,
                }),
                "auto-fit" => segs.push(Seg::AutoRepeat {
                    reps: sizes,
                    fit: true,
                }),
                n => {
                    let n: usize = n.parse().ok().filter(|&n| n >= 1)?;
                    // Lid against hostile repeat counts (the grid itself is
                    // capped by the terminal's paintable area anyway).
                    for _ in 0..n.min(1000) {
                        segs.extend(sizes.iter().cloned().map(Seg::One));
                    }
                }
            }
        } else {
            segs.push(Seg::One(parse_track_size(&tok, u, vp)?));
        }
    }
    // §7.2.3.2: the auto-repetition count is the largest N that doesn't
    // overflow the definite available space, gaps included; each repeated
    // track counts as its definite max else definite min; ≥ 1 always.
    let mut out: Vec<Track> = Vec::new();
    let fixed_sum: f32 = segs
        .iter()
        .map(|s| match s {
            Seg::One(ts) => ts
                .max
                .definite(avail)
                .or_else(|| ts.min.definite(avail))
                .unwrap_or(0.0),
            Seg::AutoRepeat { .. } => 0.0,
        })
        .sum();
    let n_fixed = segs.iter().filter(|s| matches!(s, Seg::One(_))).count();
    for seg in segs {
        match seg {
            Seg::One(ts) => out.push(Track::new(ts, false)),
            Seg::AutoRepeat { reps, fit } => {
                let rep_size: f32 = reps
                    .iter()
                    .map(|ts| {
                        let max = ts.max.definite(avail);
                        let min = ts.min.definite(avail);
                        match (max, min) {
                            (Some(mx), Some(mn)) => mx.max(mn),
                            (Some(mx), None) => mx,
                            (None, Some(mn)) => mn,
                            (None, None) => 0.0,
                        }
                    })
                    .sum();
                let k = reps.len() as f32;
                let n = match avail {
                    Some(av) if rep_size > 0.0 => {
                        let budget = av - fixed_sum - gap * (n_fixed as f32 - 1.0).max(0.0);
                        let per = rep_size + gap * k;
                        // total(N) = N·rep + gap·(N·k − 1) fits budget+gap
                        (((budget + gap) / per).floor() as isize).max(1) as usize
                    }
                    _ => 1,
                };
                for _ in 0..n.min(1000) {
                    out.extend(reps.iter().cloned().map(|ts| Track::new(ts, fit)));
                }
            }
        }
    }
    (!out.is_empty()).then_some(out)
}

// ---------------------------------------------------------------- placement

/// One `<grid-line>` as written (§8.3), before resolution.
#[derive(Clone, Debug, PartialEq)]
enum LineRaw {
    Auto,
    /// Nonzero line number (negative counts from the explicit end).
    Index(i32),
    Span(usize),
    /// A `<custom-ident>`: a named AREA edge (named lines are not tracked).
    Name(String),
}

fn parse_grid_line(v: Option<&str>) -> LineRaw {
    let Some(v) = v.map(str::trim).filter(|s| !s.is_empty()) else {
        return LineRaw::Auto;
    };
    let lower = v.to_ascii_lowercase();
    if lower == "auto" {
        return LineRaw::Auto;
    }
    if let Some(rest) = lower.strip_prefix("span") {
        let n = rest.trim().parse::<usize>().unwrap_or(1).max(1);
        return LineRaw::Span(n.min(1000));
    }
    if let Ok(n) = lower.parse::<i32>() {
        if n == 0 {
            return LineRaw::Auto; // zero is invalid (§8.3)
        }
        return LineRaw::Index(n);
    }
    // "N ident" — the integer wins (named-line filtering unsupported).
    let mut parts = lower.split_whitespace();
    if let Some(first) = parts.next()
        && let Ok(n) = first.parse::<i32>()
        && n != 0
    {
        return LineRaw::Index(n);
    }
    LineRaw::Name(v.to_string())
}

/// A resolved axis placement: definite 0-based start track, or auto, plus
/// the span count.
#[derive(Clone, Copy, Debug)]
struct AxisPlace {
    start: Option<usize>,
    span: usize,
}

/// §8.3.1: combine a start/end pair into a definite-or-auto placement.
/// `explicit_tracks` anchors negative indexes; `area` is the named area's
/// (start, end) track range for this axis when one matches.
fn resolve_axis(
    start: LineRaw,
    end: LineRaw,
    explicit_tracks: usize,
    area_of: &dyn Fn(&str) -> Option<(usize, usize)>,
) -> AxisPlace {
    let lines = explicit_tracks as i32 + 1;
    let to_index = |raw: &LineRaw, is_end: bool| -> Option<i32> {
        match raw {
            LineRaw::Index(n) => Some(if *n < 0 { lines + 1 + n } else { *n }),
            LineRaw::Name(name) => {
                // The area's track range is half-open (s..e): start edge =
                // line s+1, END edge = line e+1.
                area_of(name).map(|(s, e)| if is_end { e as i32 + 1 } else { s as i32 + 1 })
            }
            _ => None,
        }
    };
    let s_idx = to_index(&start, false);
    let e_idx = to_index(&end, true);
    match (s_idx, e_idx) {
        (Some(a), Some(b)) => {
            // Equal lines: the end becomes auto (span 1). Swapped: swap.
            let (a, b) = if a == b {
                (a, a + 1)
            } else if b < a {
                (b, a)
            } else {
                (a, b)
            };
            AxisPlace {
                start: Some((a - 1).max(0) as usize),
                span: (b - a).max(1) as usize,
            }
        }
        (Some(a), None) => {
            let span = match end {
                LineRaw::Span(n) => n,
                _ => 1,
            };
            AxisPlace {
                start: Some((a - 1).max(0) as usize),
                span,
            }
        }
        (None, Some(b)) => {
            let span = match start {
                LineRaw::Span(n) => n,
                _ => 1,
            };
            // Ends at line b, spanning back; a start before line 1 clamps
            // (implicit tracks are appended, never prepended — documented).
            let s = b - 1 - span as i32;
            AxisPlace {
                start: Some(s.max(0) as usize),
                span,
            }
        }
        (None, None) => {
            // §8.3.1: two spans drop the end one; a lone span rides auto.
            let span = match (&start, &end) {
                (LineRaw::Span(n), _) => *n,
                (_, LineRaw::Span(n)) => *n,
                _ => 1,
            };
            AxisPlace { start: None, span }
        }
    }
}

/// The dynamic occupancy grid for §8.5 (rows grow as needed).
struct Occ {
    cols: usize,
    rows: Vec<Vec<bool>>,
}

impl Occ {
    fn free(&self, r: usize, c: usize, rs: usize, cs: usize) -> bool {
        if c + cs > self.cols {
            return false;
        }
        for rr in r..r + rs {
            let Some(row) = self.rows.get(rr) else {
                continue; // beyond current rows: empty
            };
            if row[c..(c + cs).min(self.cols)].iter().any(|&b| b) {
                return false;
            }
        }
        true
    }

    fn mark(&mut self, r: usize, c: usize, rs: usize, cs: usize) {
        while self.rows.len() < r + rs {
            self.rows.push(vec![false; self.cols]);
        }
        for rr in r..r + rs {
            for cell in self.rows[rr][c..(c + cs).min(self.cols)].iter_mut() {
                *cell = true;
            }
        }
    }
}

/// A fully placed item: 0-based track ranges in both axes.
#[derive(Clone, Debug)]
pub(crate) struct Placed {
    pub cols: Range<usize>,
    pub rows: Range<usize>,
}

/// §8.5, written (like the spec) for row flow; `row_flow == false` swaps
/// the axes on entry and exit. `dense` resets the search to the grid start
/// per item.
fn auto_place(
    mut items: Vec<(AxisPlace, AxisPlace)>, // (col, row) per item
    explicit_cols: usize,
    row_flow: bool,
    dense: bool,
) -> Vec<Placed> {
    if !row_flow {
        for (c, r) in &mut items {
            std::mem::swap(c, r);
        }
    }
    // Step 3: the implicit grid's column count.
    let mut cols = explicit_cols.max(1);
    for (c, _) in &items {
        if let Some(s) = c.start {
            cols = cols.max(s + c.span);
        } else {
            cols = cols.max(c.span);
        }
    }
    let mut occ = Occ {
        cols,
        rows: Vec::new(),
    };
    let mut out: Vec<Option<Placed>> = vec![None; items.len()];
    // Step 1: definite positions in both axes.
    for (i, (c, r)) in items.iter().enumerate() {
        if let (Some(cs), Some(rs)) = (c.start, r.start) {
            occ.mark(rs, cs, r.span, c.span);
            out[i] = Some(Placed {
                cols: cs..cs + c.span,
                rows: rs..rs + r.span,
            });
        }
    }
    // Step 2: items locked to a definite row.
    let mut row_cursor: std::collections::HashMap<usize, usize> = std::collections::HashMap::new();
    for (i, (c, r)) in items.iter().enumerate() {
        if out[i].is_some() || c.start.is_some() || r.start.is_none() {
            continue;
        }
        let rs = r.start.unwrap();
        let from = if dense {
            0
        } else {
            *row_cursor.get(&rs).unwrap_or(&0)
        };
        let mut cc = from;
        while !occ.free(rs, cc, r.span, c.span) {
            cc += 1;
            if cc + c.span > occ.cols {
                // No room in the row: overlap is not allowed here; grow
                // columns only for span overflow (kept within the row).
                cc = occ.cols.saturating_sub(c.span);
                break;
            }
        }
        occ.mark(rs, cc, r.span, c.span);
        row_cursor.insert(rs, cc + c.span);
        out[i] = Some(Placed {
            cols: cc..cc + c.span,
            rows: rs..rs + r.span,
        });
    }
    // Step 4: the auto-placement cursor.
    let (mut cur_r, mut cur_c) = (0usize, 0usize);
    for (i, (c, r)) in items.iter().enumerate() {
        if out[i].is_some() {
            continue;
        }
        if dense {
            cur_r = 0;
            cur_c = 0;
        }
        let (rs, cs) = if let Some(cs) = c.start {
            // Definite column: walk rows at that column.
            if dense {
                cur_r = 0;
            } else if cs < cur_c {
                cur_r += 1;
            }
            let mut rr = cur_r;
            while !occ.free(rr, cs, r.span, c.span) {
                rr += 1;
            }
            (rr, cs)
        } else {
            // Fully auto: scan columns, overflow to the next row.
            loop {
                if cur_c + c.span <= occ.cols && occ.free(cur_r, cur_c, r.span, c.span) {
                    break (cur_r, cur_c);
                }
                if cur_c + c.span >= occ.cols {
                    cur_r += 1;
                    cur_c = 0;
                } else {
                    cur_c += 1;
                }
            }
        };
        occ.mark(rs, cs, r.span, c.span);
        cur_r = rs;
        cur_c = cs; // sparse flow continues from here
        out[i] = Some(Placed {
            cols: cs..cs + c.span,
            rows: rs..rs + r.span,
        });
    }
    let mut placed: Vec<Placed> = out.into_iter().map(Option::unwrap).collect();
    if !row_flow {
        for p in &mut placed {
            std::mem::swap(&mut p.cols, &mut p.rows);
        }
    }
    placed
}

/// `name → (row range, column range)` of the named areas.
type AreaMap = std::collections::HashMap<String, (Range<usize>, Range<usize>)>;

/// Parse `grid-template-areas` (§7.3) into the area map plus the template's
/// row/column counts. Non-rectangular or ragged definitions invalidate the
/// whole declaration.
fn parse_areas(value: &str) -> Option<(AreaMap, usize, usize)> {
    let v = value.trim();
    if v.is_empty() || v.eq_ignore_ascii_case("none") {
        return None;
    }
    // Row strings are quoted; tokenize each into cell names / null cells.
    let mut rows: Vec<Vec<String>> = Vec::new();
    let mut rest = v;
    while let Some(q) = rest.find(['"', '\'']) {
        let quote = rest.as_bytes()[q] as char;
        let tail = &rest[q + 1..];
        let end = tail.find(quote)?;
        let row: Vec<String> = tail[..end]
            .split_whitespace()
            .map(|t| t.to_string())
            .collect();
        if !row.is_empty() {
            rows.push(row);
        }
        rest = &tail[end + 1..];
    }
    if rows.is_empty() {
        return None;
    }
    let ncols = rows[0].len();
    if rows.iter().any(|r| r.len() != ncols) {
        return None; // ragged
    }
    let mut map: AreaMap = std::collections::HashMap::new();
    for (r, row) in rows.iter().enumerate() {
        for (c, name) in row.iter().enumerate() {
            if name.starts_with('.') {
                continue; // null cell
            }
            let key = name.to_ascii_lowercase();
            match map.get_mut(&key) {
                None => {
                    map.insert(key, (r..r + 1, c..c + 1));
                }
                Some((rr, cc)) => {
                    rr.start = rr.start.min(r);
                    rr.end = rr.end.max(r + 1);
                    cc.start = cc.start.min(c);
                    cc.end = cc.end.max(c + 1);
                }
            }
        }
    }
    // Rectangularity: every named area's cells must exactly tile its rect.
    for (name, (rr, cc)) in &map {
        for r in rr.clone() {
            for c in cc.clone() {
                if rows[r][c].to_ascii_lowercase() != *name {
                    return None;
                }
            }
        }
    }
    Some((map, rows.len(), ncols))
}

// ------------------------------------------------------------- §11 sizing

/// An item's contribution to the tracks it spans in one axis.
struct Contrib {
    tracks: Range<usize>,
    min: f32,
    max: f32,
}

/// The §11 track sizing algorithm for one axis. `avail` is the definite
/// available grid space (content-box, this axis); `gap` the used gutter;
/// `stretch` whether the axis' content-distribution is normal/stretch
/// (§11.8). Contributions arrive pre-measured (margin-box).
fn size_tracks(
    tracks: &mut [Track],
    items: &[Contrib],
    avail: Option<f32>,
    gap: f32,
    stretch: bool,
) {
    let n_live = tracks.iter().filter(|t| !t.collapsed).count();
    let gaps_total = gap * (n_live.saturating_sub(1)) as f32;
    let track_avail = avail.map(|a| (a - gaps_total).max(0.0));

    // §11.4 initialize.
    for t in tracks.iter_mut() {
        if t.collapsed {
            t.base = 0.0;
            t.limit = 0.0;
            continue;
        }
        t.base = t.size.min.definite(track_avail).unwrap_or(0.0);
        t.limit = match &t.size.max {
            TrackFn::Fixed(l) => l
                .resolve(track_avail)
                .map(|v| v.max(0.0))
                .unwrap_or(f32::INFINITY),
            _ => f32::INFINITY,
        };
        if t.limit < t.base {
            t.limit = t.base;
        }
    }

    // Internal gap span helper: an item spanning k live tracks crosses
    // (k−1) gutters, which the spec treats as fixed tracks.
    let span_gaps = |r: &Range<usize>, tracks: &[Track]| -> f32 {
        let live = tracks[r.clone()].iter().filter(|t| !t.collapsed).count();
        gap * live.saturating_sub(1) as f32
    };

    // §11.5 resolve intrinsic track sizes, by ascending span, flexible-
    // track spanners last.
    let crosses_fr = |r: &Range<usize>, tracks: &[Track]| {
        tracks[r.clone()]
            .iter()
            .any(|t| matches!(t.size.max, TrackFn::Fr(_)))
    };
    let mut spans: Vec<usize> = items
        .iter()
        .filter(|c| !crosses_fr(&c.tracks, tracks))
        .map(|c| c.tracks.len())
        .collect();
    spans.sort_unstable();
    spans.dedup();
    for span in spans {
        let group: Vec<&Contrib> = items
            .iter()
            .filter(|c| c.tracks.len() == span && !crosses_fr(&c.tracks, tracks))
            .collect();
        if group.is_empty() {
            continue;
        }
        if span == 1 {
            // "Size tracks to fit non-spanning items."
            for c in &group {
                let ti = c.tracks.start;
                let t = &mut tracks[ti];
                if t.collapsed {
                    continue;
                }
                match &t.size.min {
                    TrackFn::MinContent | TrackFn::Auto => t.base = t.base.max(c.min),
                    TrackFn::MaxContent => t.base = t.base.max(c.max),
                    _ => {}
                }
                match &t.size.max {
                    TrackFn::MinContent => {
                        t.limit = if t.limit.is_infinite() {
                            c.min
                        } else {
                            t.limit.max(c.min)
                        };
                    }
                    TrackFn::Auto | TrackFn::MaxContent => {
                        t.limit = if t.limit.is_infinite() {
                            c.max
                        } else {
                            t.limit.max(c.max)
                        };
                    }
                    TrackFn::FitContent(l) => {
                        let cap = l.resolve(track_avail).unwrap_or(f32::INFINITY);
                        let v = if t.limit.is_infinite() {
                            c.max
                        } else {
                            t.limit.max(c.max)
                        };
                        t.limit = v.min(cap).max(t.base);
                    }
                    _ => {}
                }
                if t.limit < t.base {
                    t.limit = t.base;
                }
            }
            continue;
        }
        // Spanning items (§11.5 steps 3+, with §11.5.1 distribution).
        distribute_group(tracks, &group, span_gaps, false);
        distribute_group(tracks, &group, span_gaps, true);
    }
    // Flexible-track spanners: distribute minimum contributions to the
    // flexible tracks by flex-factor ratio (all together, §11.5 last step).
    let fr_items: Vec<&Contrib> = items
        .iter()
        .filter(|c| crosses_fr(&c.tracks, tracks))
        .collect();
    for c in fr_items {
        let others: f32 = tracks[c.tracks.clone()]
            .iter()
            .filter(|t| !matches!(t.size.max, TrackFn::Fr(_)))
            .map(|t| t.base)
            .sum();
        let space = (c.min - others - span_gaps(&c.tracks, tracks)).max(0.0);
        let factors: f32 = tracks[c.tracks.clone()]
            .iter()
            .filter_map(|t| match t.size.max {
                TrackFn::Fr(f) => Some(f),
                _ => None,
            })
            .sum();
        let denom = factors.max(1.0);
        for t in tracks[c.tracks.clone()].iter_mut() {
            if let TrackFn::Fr(f) = t.size.max {
                t.base = t.base.max(space * (f / denom));
            }
        }
    }
    // Any remaining infinite growth limit → base size.
    for t in tracks.iter_mut() {
        if t.limit.is_infinite() {
            t.limit = t.base;
        }
    }

    // §11.6 maximize: distribute positive free space equally to bases,
    // freezing at growth limits.
    if let Some(av) = track_avail {
        let mut free = av - tracks.iter().map(|t| t.base).sum::<f32>();
        if free > 0.0 {
            loop {
                let open: Vec<usize> = (0..tracks.len())
                    .filter(|&i| !tracks[i].collapsed && tracks[i].base < tracks[i].limit)
                    .collect();
                if open.is_empty() || free <= 0.001 {
                    break;
                }
                let share = free / open.len() as f32;
                let mut used = 0.0;
                for &i in &open {
                    let grow = share.min(tracks[i].limit - tracks[i].base);
                    tracks[i].base += grow;
                    used += grow;
                }
                free -= used;
                if used <= 0.0 {
                    break;
                }
            }
        }
    }

    // §11.7 expand flexible tracks.
    let has_fr = tracks.iter().any(|t| matches!(t.size.max, TrackFn::Fr(_)));
    if has_fr {
        let fr_size = match track_avail {
            Some(av) => {
                let free = av - tracks.iter().map(|t| t.base).sum::<f32>();
                if free > 0.0 {
                    find_fr_size(tracks, av)
                } else {
                    0.0
                }
            }
            None => {
                // Indefinite free space: each flexible track's base / factor.
                tracks
                    .iter()
                    .filter_map(|t| match t.size.max {
                        TrackFn::Fr(f) if f > 1.0 => Some(t.base / f),
                        TrackFn::Fr(_) => Some(t.base),
                        _ => None,
                    })
                    .fold(0.0f32, f32::max)
            }
        };
        for t in tracks.iter_mut() {
            if t.collapsed {
                continue;
            }
            if let TrackFn::Fr(f) = t.size.max {
                t.base = t.base.max(fr_size * f);
            }
        }
    }

    // §11.8 stretch auto tracks.
    if stretch && let Some(av) = track_avail {
        let free = av - tracks.iter().map(|t| t.base).sum::<f32>();
        if free > 0.0 {
            let autos: Vec<usize> = (0..tracks.len())
                .filter(|&i| !tracks[i].collapsed && matches!(tracks[i].size.max, TrackFn::Auto))
                .collect();
            if !autos.is_empty() {
                let share = free / autos.len() as f32;
                for i in autos {
                    tracks[i].base += share;
                }
            }
        }
    }
}

/// §11.5's spanning-item phases over one span group: `limits == false`
/// distributes contributions into BASE sizes (minimum then max-content
/// minimums), `true` into GROWTH LIMITS (with the infinitely-growable
/// marking). Distribution per §11.5.1: equally up to limits, then beyond
/// limits into intrinsic-max tracks.
fn distribute_group(
    tracks: &mut [Track],
    group: &[&Contrib],
    span_gaps: impl Fn(&Range<usize>, &[Track]) -> f32,
    limits: bool,
) {
    let mut planned: std::collections::HashMap<usize, f32> = std::collections::HashMap::new();
    // Two passes per §11.5: min-content contributions, then max-content.
    for use_max in [false, true] {
        planned.clear();
        for c in group {
            let contribution = if use_max { c.max } else { c.min };
            let affected: Vec<usize> = c
                .tracks
                .clone()
                .filter(|&i| {
                    if tracks[i].collapsed {
                        return false;
                    }
                    if limits {
                        tracks[i].size.max.is_intrinsic()
                    } else if use_max {
                        // The max-content pass only affects max-content mins.
                        matches!(tracks[i].size.min, TrackFn::MaxContent)
                    } else {
                        tracks[i].size.min.is_intrinsic()
                    }
                })
                .collect();
            if affected.is_empty() {
                continue;
            }
            let spanned_sum: f32 = c
                .tracks
                .clone()
                .map(|i| {
                    if limits {
                        if tracks[i].limit.is_infinite() {
                            tracks[i].base
                        } else {
                            tracks[i].limit
                        }
                    } else {
                        tracks[i].base
                    }
                })
                .sum();
            let mut space = contribution - spanned_sum - span_gaps(&c.tracks, tracks);
            if space <= 0.0 {
                continue;
            }
            // Equal distribution up to limits, then beyond into
            // intrinsic-max tracks (§11.5.1 steps 2 + 4).
            let mut inc: std::collections::HashMap<usize, f32> = std::collections::HashMap::new();
            let mut open: Vec<usize> = affected.clone();
            while space > 0.001 && !open.is_empty() {
                let share = space / open.len() as f32;
                let mut used = 0.0;
                let mut next: Vec<usize> = Vec::new();
                for &i in &open {
                    let cur = tracks[i].base + inc.get(&i).copied().unwrap_or(0.0);
                    let cap = if limits {
                        if tracks[i].limit.is_infinite() || tracks[i].inf_growable {
                            f32::INFINITY
                        } else {
                            tracks[i].limit
                        }
                    } else {
                        tracks[i].limit
                    };
                    let room = (cap - cur).max(0.0);
                    let grow = share.min(room);
                    *inc.entry(i).or_default() += grow;
                    used += grow;
                    if grow >= share - 0.0001 {
                        next.push(i);
                    }
                }
                space -= used;
                open = next;
                if used <= 0.0 {
                    break;
                }
            }
            // Beyond limits: intrinsic-max tracks (else all affected).
            if space > 0.001 {
                let beyond: Vec<usize> = affected
                    .iter()
                    .copied()
                    .filter(|&i| tracks[i].size.max.is_intrinsic())
                    .collect();
                let set = if beyond.is_empty() {
                    &affected
                } else {
                    &beyond
                };
                let share = space / set.len() as f32;
                for &i in set {
                    *inc.entry(i).or_default() += share;
                }
            }
            for (i, v) in inc {
                let p = planned.entry(i).or_default();
                *p = p.max(v);
            }
        }
        // Commit the group's planned increases.
        for (&i, &v) in &planned {
            if v <= 0.0 {
                continue;
            }
            if limits {
                if tracks[i].limit.is_infinite() {
                    tracks[i].limit = tracks[i].base + v;
                    tracks[i].inf_growable = true;
                } else {
                    tracks[i].limit += v;
                }
            } else {
                tracks[i].base += v;
                if tracks[i].limit < tracks[i].base {
                    tracks[i].limit = tracks[i].base;
                }
            }
        }
    }
}

/// §11.7.1 find-the-size-of-an-fr: the largest fr size that fills `space`
/// exactly, iteratively treating too-small flexible tracks as inflexible.
fn find_fr_size(tracks: &[Track], space: f32) -> f32 {
    // Collapsed (auto-fit) tracks are never flexible: they would siphon
    // fr space into zero-width tracks otherwise.
    let mut inflexible: Vec<bool> = tracks
        .iter()
        .map(|t| t.collapsed || !matches!(t.size.max, TrackFn::Fr(_)))
        .collect();
    loop {
        let leftover: f32 = space
            - tracks
                .iter()
                .zip(&inflexible)
                .map(|(t, &inf)| if inf { t.base } else { 0.0 })
                .sum::<f32>();
        let factor_sum: f32 = tracks
            .iter()
            .zip(&inflexible)
            .filter(|(_, inf)| !**inf)
            .map(|(t, _)| match t.size.max {
                TrackFn::Fr(f) => f,
                _ => 0.0,
            })
            .sum();
        if factor_sum <= 0.0 {
            return 0.0;
        }
        let hyp = leftover / factor_sum.max(1.0);
        let mut restarted = false;
        for (i, t) in tracks.iter().enumerate() {
            if inflexible[i] {
                continue;
            }
            if let TrackFn::Fr(f) = t.size.max
                && hyp * f < t.base
            {
                inflexible[i] = true;
                restarted = true;
            }
        }
        if !restarted {
            return hyp.max(0.0);
        }
    }
}

/// Map a content-distribution keyword onto the shared distribution model.
fn dist_of(v: Option<&str>) -> Justify {
    match v.unwrap_or("").trim().to_ascii_lowercase().as_str() {
        "end" | "flex-end" | "right" => Justify::End,
        "center" => Justify::Center,
        "space-between" => Justify::Between,
        "space-around" => Justify::Around,
        "space-evenly" => Justify::Evenly,
        _ => Justify::Start,
    }
}

/// Whether a content-distribution keyword stretches auto tracks (§11.8:
/// `normal` or `stretch`).
fn dist_stretches(v: Option<&str>) -> bool {
    matches!(
        v.unwrap_or("normal").trim().to_ascii_lowercase().as_str(),
        "normal" | "stretch" | ""
    )
}

/// A self-alignment keyword (justify-self/align-self and their *-items
/// defaults) mapped to the shared AlignItem model. `auto`/absent falls back
/// to the container's *-items value; `normal` behaves as stretch for
/// non-replaced grid items (css-align §6.1.2).
fn self_align(own: Option<&str>, items_default: super::flex::AlignItem) -> super::flex::AlignItem {
    use super::flex::AlignItem;
    match own.unwrap_or("").trim().to_ascii_lowercase().as_str() {
        "start" | "flex-start" | "self-start" | "left" => AlignItem::Start,
        "end" | "flex-end" | "self-end" | "right" => AlignItem::End,
        "center" => AlignItem::Center,
        "stretch" | "normal" => AlignItem::Stretch,
        "baseline" | "first baseline" | "last baseline" => AlignItem::Start,
        _ => items_default,
    }
}

impl Flow<'_> {
    /// Lay a grid container's items (css-grid-1): placement → column
    /// sizing (§11) → item layout at real track widths → row sizing (§11 in
    /// the block axis, contributions = laid heights) → §10.4/§10.5 track
    /// alignment and §6.6-adjacent item alignment.
    #[allow(clippy::too_many_arguments)]
    pub(super) fn grid_content<'t>(
        &self,
        b: &'t BoxNode,
        items: &'t [BoxNode],
        content_x: f32,
        content_top: f32,
        content_w: f32,
        def_ch: Option<f32>,
        inl: &InlineStyle,
        anchors: &mut Vec<(NodeId, f32)>,
    ) -> (Vec<Frag<'t>>, f32) {
        use super::flex::AlignItem;
        let node = b.node;
        let u = Units::of(self.dom, node);
        let cv = |p: &str| self.dom.computed_value(node, p);

        // Gaps: `gap` = <row-gap> <column-gap>; longhands win.
        let (short_row, short_col) = {
            let g = cv("gap").unwrap_or_default();
            let mut parts = g.split_whitespace();
            let a = parts.next().map(str::to_string);
            let bb = parts.next().map(str::to_string).or_else(|| a.clone());
            (a, bb)
        };
        let parse_gap = |long: Option<String>, short: Option<String>, basis: Option<f32>| {
            long.or(short)
                .and_then(|v| Len::parse(&v, u, self.vp))
                .and_then(|l| l.resolve(basis))
                .unwrap_or(0.0)
                .max(0.0)
        };
        let gap_col = parse_gap(cv("column-gap"), short_col, Some(content_w));
        let gap_row = parse_gap(cv("row-gap"), short_row, def_ch);

        // Named areas + explicit templates.
        let areas = cv("grid-template-areas").as_deref().and_then(parse_areas);
        let (area_rows_n, area_cols_n) = areas.as_ref().map_or((0, 0), |(_, r, c)| (*r, *c));
        let auto_ts = || TrackSize {
            min: TrackFn::Auto,
            max: TrackFn::Auto,
        };
        let mut cols: Vec<Track> = cv("grid-template-columns")
            .as_deref()
            .and_then(|v| parse_template(v, u, self.vp, Some(content_w), gap_col))
            .unwrap_or_default();
        let mut rows: Vec<Track> = cv("grid-template-rows")
            .as_deref()
            .and_then(|v| parse_template(v, u, self.vp, def_ch, gap_row))
            .unwrap_or_default();
        while cols.len() < area_cols_n {
            cols.push(Track::new(auto_ts(), false));
        }
        while rows.len() < area_rows_n {
            rows.push(Track::new(auto_ts(), false));
        }
        let explicit_cols = cols.len();
        let explicit_rows = rows.len();

        let flow_v = cv("grid-auto-flow")
            .unwrap_or_default()
            .to_ascii_lowercase();
        let row_flow = !flow_v.contains("column");
        let dense = flow_v.contains("dense");

        // §8.5 note: order-modified document order.
        let mut idx: Vec<usize> = (0..items.len()).collect();
        idx.sort_by_key(|&i| self.order_of(items[i].node));
        let ordered: Vec<&'t BoxNode> = idx.iter().map(|&i| &items[i]).collect();

        // Per-item grid lines: grid-area, overridden by grid-row/column
        // shorthands, overridden by the *-start/*-end longhands.
        let area_col = |name: &str| -> Option<(usize, usize)> {
            areas
                .as_ref()
                .and_then(|(m, _, _)| m.get(&name.to_ascii_lowercase()))
                .map(|(_, cc)| (cc.start, cc.end))
        };
        let area_row = |name: &str| -> Option<(usize, usize)> {
            areas
                .as_ref()
                .and_then(|(m, _, _)| m.get(&name.to_ascii_lowercase()))
                .map(|(rr, _)| (rr.start, rr.end))
        };
        let placements: Vec<(AxisPlace, AxisPlace)> = ordered
            .iter()
            .map(|it| {
                let icv = |p: &str| {
                    if it.node == NO_NODE {
                        None
                    } else {
                        self.dom.computed_value(it.node, p)
                    }
                };
                // grid-area: row-start / col-start / row-end / col-end with
                // the §8.4 backfill (a lone ident names the whole area).
                let ga = icv("grid-area").unwrap_or_default();
                let parts: Vec<&str> = if ga.trim().is_empty() {
                    Vec::new()
                } else {
                    ga.split('/').map(str::trim).collect()
                };
                let part = |i: usize| parts.get(i).copied();
                let backfill = |i: usize, from: Option<&str>| -> LineRaw {
                    match part(i) {
                        Some(v) => parse_grid_line(Some(v)),
                        None => match from {
                            Some(v) if matches!(parse_grid_line(Some(v)), LineRaw::Name(_)) => {
                                parse_grid_line(Some(v))
                            }
                            _ => LineRaw::Auto,
                        },
                    }
                };
                let mut rs = backfill(0, None);
                let mut cs = backfill(1, part(0));
                let mut re = backfill(2, part(0));
                let mut ce = backfill(3, part(1).or(part(0)));
                if let Some(v) = icv("grid-row") {
                    let (a, b2) = v
                        .split_once('/')
                        .map_or((v.as_str(), None), |(a, b2)| (a, Some(b2)));
                    rs = parse_grid_line(Some(a));
                    re = parse_grid_line(b2);
                }
                if let Some(v) = icv("grid-column") {
                    let (a, b2) = v
                        .split_once('/')
                        .map_or((v.as_str(), None), |(a, b2)| (a, Some(b2)));
                    cs = parse_grid_line(Some(a));
                    ce = parse_grid_line(b2);
                }
                if let Some(v) = icv("grid-row-start") {
                    rs = parse_grid_line(Some(&v));
                }
                if let Some(v) = icv("grid-row-end") {
                    re = parse_grid_line(Some(&v));
                }
                if let Some(v) = icv("grid-column-start") {
                    cs = parse_grid_line(Some(&v));
                }
                if let Some(v) = icv("grid-column-end") {
                    ce = parse_grid_line(Some(&v));
                }
                (
                    resolve_axis(cs, ce, explicit_cols, &area_col),
                    resolve_axis(rs, re, explicit_rows, &area_row),
                )
            })
            .collect();
        // §8.5 works in flow-relative axes: its "columns" are the real
        // columns under row flow, the real ROWS under column flow.
        let minor_tracks = if row_flow {
            explicit_cols
        } else {
            explicit_rows
        };
        let placed = auto_place(placements, minor_tracks.max(1), row_flow, dense);

        // Implicit tracks from grid-auto-columns/rows (a list cycles).
        let auto_list = |prop: &str| -> Vec<TrackSize> {
            let list: Vec<TrackSize> = cv(prop)
                .as_deref()
                .map(|v| {
                    split_track_tokens(v)
                        .iter()
                        .filter_map(|t| parse_track_size(t, u, self.vp))
                        .collect()
                })
                .unwrap_or_default();
            if list.is_empty() {
                vec![auto_ts()]
            } else {
                list
            }
        };
        let auto_cols = auto_list("grid-auto-columns");
        let auto_rows = auto_list("grid-auto-rows");
        let need_cols = placed.iter().map(|p| p.cols.end).max().unwrap_or(0);
        let need_rows = placed.iter().map(|p| p.rows.end).max().unwrap_or(0);
        while cols.len() < need_cols {
            let i = (cols.len() - explicit_cols) % auto_cols.len();
            cols.push(Track::new(auto_cols[i].clone(), false));
        }
        while rows.len() < need_rows {
            let i = (rows.len() - explicit_rows) % auto_rows.len();
            rows.push(Track::new(auto_rows[i].clone(), false));
        }

        // auto-fit: collapse repetition tracks no item spans (§7.2.3.2).
        for (ci, t) in cols.iter_mut().enumerate() {
            if t.collapsible && !placed.iter().any(|p| p.cols.contains(&ci)) {
                t.collapsed = true;
            }
        }
        for (ri, t) in rows.iter_mut().enumerate() {
            if t.collapsible && !placed.iter().any(|p| p.rows.contains(&ri)) {
                t.collapsed = true;
            }
        }

        // ---- §11 column sizing from intrinsic contributions ----
        let col_contribs: Vec<Contrib> = ordered
            .iter()
            .zip(&placed)
            .map(|(it, p)| Contrib {
                tracks: p.cols.clone(),
                min: self.contribution(it, IMode::Min, inl),
                max: self.contribution(it, IMode::Max, inl),
            })
            .collect();
        let jc = cv("justify-content");
        size_tracks(
            &mut cols,
            &col_contribs,
            Some(content_w),
            gap_col,
            dist_stretches(jc.as_deref()),
        );

        // Track positions + content-distribution of leftover main space.
        let positions =
            |tracks: &[Track], gap: f32, avail: Option<f32>, dist: Justify| -> Vec<f32> {
                let live = tracks.iter().filter(|t| !t.collapsed).count();
                let total: f32 = tracks.iter().map(|t| t.base).sum::<f32>()
                    + gap * live.saturating_sub(1) as f32;
                let free = avail.map_or(0.0, |a| a - total);
                let (lead, between) = justify_offsets(dist, free, live);
                let mut xs = Vec::with_capacity(tracks.len());
                let mut x = lead.max(0.0);
                let mut seen_live = 0usize;
                for t in tracks {
                    if t.collapsed {
                        xs.push(x);
                        continue;
                    }
                    if seen_live > 0 {
                        x += gap + between;
                    }
                    xs.push(x);
                    x += t.base;
                    seen_live += 1;
                }
                xs
            };
        let col_x = positions(&cols, gap_col, Some(content_w), dist_of(jc.as_deref()));

        // ---- lay items at their area widths ----
        let justify_items = {
            let ji = cv("justify-items").or_else(|| {
                cv("place-items")
                    .map(|v| v.split('/').nth(1).unwrap_or(v.as_str()).trim().to_string())
            });
            self_align(ji.as_deref(), AlignItem::Stretch)
        };
        let align_items = {
            let ai = cv("align-items").or_else(|| {
                cv("place-items").map(|v| v.split('/').next().unwrap_or("").trim().to_string())
            });
            self_align(ai.as_deref(), AlignItem::Stretch)
        };
        struct GItem<'t> {
            it: &'t BoxNode,
            frag: Frag<'t>,
            anchors: Vec<(NodeId, f32)>,
            m: [f32; 4],
            auto: [bool; 4],
            align: AlignItem,
            border_x: f32,
            /// The item's grid-area width (its containing block — css-grid
            /// §9.1; the §9.4.3 relative-offset percentage basis).
            area_w: f32,
            /// The item's cross (height) property is auto — stretch applies.
            cross_auto: bool,
        }
        let mut gitems: Vec<GItem<'t>> = Vec::with_capacity(ordered.len());
        for (it, p) in ordered.iter().zip(&placed) {
            let s = &it.style;
            let (m, auto) = self.margins_of(s, content_w);
            let area_x = col_x[p.cols.start];
            let last = p.cols.end - 1;
            let area_w = (col_x[last] + cols[last].base - area_x).max(0.0);
            let bp_l = s.border[LEFT] + self.pad(s, LEFT, area_w);
            let bp_r = s.border[RIGHT] + self.pad(s, RIGHT, area_w);
            let bp_h = bp_l + bp_r;
            let to_content = |v: f32| {
                if s.border_box {
                    (v - bp_h).max(0.0)
                } else {
                    v.max(0.0)
                }
            };
            let icv = |pn: &str| {
                if it.node == NO_NODE {
                    None
                } else {
                    self.dom.computed_value(it.node, pn)
                }
            };
            let justify = {
                let js = icv("justify-self").or_else(|| {
                    icv("place-self")
                        .map(|v| v.split('/').nth(1).unwrap_or(v.as_str()).trim().to_string())
                });
                self_align(js.as_deref(), justify_items)
            };
            let width_def = s.width.resolve(Some(area_w)).map(to_content);
            let avail_c = (area_w - m[LEFT] - m[RIGHT] - bp_h).max(0.0);
            let w = match width_def {
                Some(v) => v,
                None if justify == AlignItem::Stretch && !auto[LEFT] && !auto[RIGHT] => avail_c,
                None => {
                    let minc = self.intrinsic_w(it, IMode::Min, inl);
                    let maxc = self.intrinsic_w(it, IMode::Max, inl).max(minc);
                    avail_c.max(minc).min(maxc)
                }
            };
            let def_h = s.height.resolve(def_ch).map(|v| v.max(0.0));
            let (frag, anc) = self.item_frag(it, w.max(0.0), area_w, def_h, inl);
            // Horizontal placement within the area (css-align self-alignment;
            // auto margins win over the alignment keyword).
            let extra = area_w - (frag.w + m[LEFT] + m[RIGHT]);
            let shift = super::flow::cross_shift(extra, auto[LEFT], auto[RIGHT], justify);
            gitems.push(GItem {
                it,
                border_x: area_x + shift + m[LEFT],
                cross_auto: matches!(s.height, Len::Auto),
                area_w,
                frag,
                anchors: anc,
                m,
                auto,
                align: {
                    let asf = icv("align-self").or_else(|| {
                        icv("place-self")
                            .map(|v| v.split('/').next().unwrap_or("").trim().to_string())
                    });
                    self_align(asf.as_deref(), align_items)
                },
            });
        }

        // ---- §11 row sizing from laid heights ----
        let row_contribs: Vec<Contrib> = gitems
            .iter()
            .zip(&placed)
            .map(|(g, p)| {
                let h = g.frag.h + g.m[TOP] + g.m[BOTTOM];
                Contrib {
                    tracks: p.rows.clone(),
                    min: h,
                    max: h,
                }
            })
            .collect();
        let ac = cv("align-content");
        size_tracks(
            &mut rows,
            &row_contribs,
            def_ch,
            gap_row,
            dist_stretches(ac.as_deref()),
        );
        let row_y = positions(&rows, gap_row, def_ch, dist_of(ac.as_deref()));

        // ---- finalize: vertical alignment within row areas, translate ----
        let mut frags: Vec<Frag<'t>> = Vec::with_capacity(gitems.len());
        for (g, p) in gitems.iter_mut().zip(&placed) {
            let area_y = row_y[p.rows.start];
            let last = p.rows.end - 1;
            let area_h = (row_y[last] + rows[last].base - area_y).max(0.0);
            if g.align == AlignItem::Stretch && g.cross_auto && !g.auto[TOP] && !g.auto[BOTTOM] {
                g.frag.h = g.frag.h.max(area_h - g.m[TOP] - g.m[BOTTOM]).max(0.0);
            }
            let extra = area_h - (g.frag.h + g.m[TOP] + g.m[BOTTOM]);
            let shift = super::flow::cross_shift(extra, g.auto[TOP], g.auto[BOTTOM], g.align);
            // §9.4.3 relative offset + transform translation — a grid item's
            // containing block is its grid area (css-grid §9.1).
            let (rx, ry) =
                self.paint_offset(&g.it.style, g.area_w, Some(area_h), g.frag.w, g.frag.h);
            let dx = content_x + g.border_x + rx;
            let dy = content_top + area_y + shift + g.m[TOP] + ry;
            let mut frag = std::mem::replace(&mut g.frag, Frag::empty());
            Flow::offset_frag(&mut frag, dx, dy);
            for &(n, y) in &g.anchors {
                anchors.push((n, y + dy));
            }
            frags.push(frag);
        }
        let live_rows = rows.iter().filter(|t| !t.collapsed).count();
        let content_h =
            rows.iter().map(|t| t.base).sum::<f32>() + gap_row * live_rows.saturating_sub(1) as f32;
        (frags, content_h.max(0.0))
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::layout::Units;

    fn u() -> Units {
        Units::default()
    }

    fn vpx() -> Vp {
        Vp { w: 640.0, h: 384.0 }
    }

    fn tpl(s: &str, avail: f32, gap: f32) -> Vec<Track> {
        parse_template(s, u(), vpx(), Some(avail), gap).expect(s)
    }

    #[test]
    fn parses_track_grammar() {
        let t = tpl(
            "100px 1fr minmax(50px, max-content) fit-content(200px) auto",
            640.0,
            0.0,
        );
        assert_eq!(t.len(), 5);
        assert!(matches!(t[1].size.min, TrackFn::Auto));
        assert!(matches!(t[1].size.max, TrackFn::Fr(f) if f == 1.0));
        assert!(matches!(t[2].size.max, TrackFn::MaxContent));
        assert!(matches!(t[3].size.max, TrackFn::FitContent(_)));
    }

    #[test]
    fn auto_fill_counts_repetitions() {
        // 640px, 100px tracks, 10px gaps: N·100 + (N−1)·10 ≤ 640 → N = 5.
        let t = tpl("repeat(auto-fill, 100px)", 640.0, 10.0);
        assert_eq!(t.len(), 5);
        // minmax(16rem=256px, 1fr): definite min governs → 2 fit in 640.
        let t = tpl("repeat(auto-fill, minmax(16rem, 1fr))", 640.0, 0.0);
        assert_eq!(t.len(), 2);
    }

    #[test]
    fn fr_expansion_fills_definite_space() {
        let mut t = tpl("100px 1fr 2fr", 700.0, 0.0);
        size_tracks(&mut t, &[], Some(700.0), 0.0, true);
        assert_eq!(t[0].base, 100.0);
        assert!((t[1].base - 200.0).abs() < 0.5);
        assert!((t[2].base - 400.0).abs() < 0.5);
    }

    #[test]
    fn fr_floor_at_base_marks_inflexible() {
        // §11.7.1: content gives track 0 a 250px base; the hypothetical fr
        // (300/2 = 150) undershoots it, so track 0 goes inflexible and
        // track 1 re-divides the leftover 50px.
        let mut t = tpl("1fr 1fr", 300.0, 0.0);
        let items = [Contrib {
            tracks: 0..1,
            min: 250.0,
            max: 250.0,
        }];
        size_tracks(&mut t, &items, Some(300.0), 0.0, true);
        assert_eq!(t[0].base, 250.0);
        assert!((t[1].base - 50.0).abs() < 0.5, "got {}", t[1].base);
    }

    #[test]
    fn auto_tracks_stretch_under_normal_distribution() {
        let mut t = tpl("auto auto", 600.0, 0.0);
        let items = [
            Contrib {
                tracks: 0..1,
                min: 80.0,
                max: 80.0,
            },
            Contrib {
                tracks: 1..2,
                min: 120.0,
                max: 120.0,
            },
        ];
        size_tracks(&mut t, &items, Some(600.0), 0.0, true);
        // Content 80+120, leftover 400 split equally (§11.8).
        assert!((t[0].base - 280.0).abs() < 0.5);
        assert!((t[1].base - 320.0).abs() < 0.5);
    }

    #[test]
    fn spanning_item_distributes_to_intrinsic_tracks() {
        let mut t = tpl("auto auto", 600.0, 0.0);
        let items = [
            Contrib {
                tracks: 0..1,
                min: 50.0,
                max: 50.0,
            },
            Contrib {
                tracks: 0..2,
                min: 300.0,
                max: 300.0,
            },
        ];
        size_tracks(&mut t, &items, Some(600.0), 0.0, false);
        let sum = t[0].base + t[1].base;
        assert!(sum >= 300.0 - 0.5, "spanner accommodated: {sum}");
    }

    #[test]
    fn areas_parse_and_validate() {
        let (map, rows, cols) =
            parse_areas(r#""head head" "nav  main" "foot foot""#).expect("valid");
        assert_eq!((rows, cols), (3, 2));
        assert_eq!(map["head"], (0..1, 0..2));
        assert_eq!(map["nav"], (1..2, 0..1));
        assert_eq!(map["main"], (1..2, 1..2));
        // Non-rectangular → invalid.
        assert!(parse_areas(r#""a a" "a b""#).is_none());
        // Ragged → invalid.
        assert!(parse_areas(r#""a a" "b""#).is_none());
    }

    #[test]
    fn line_resolution_rules() {
        let no_area = |_: &str| None;
        // 3 explicit tracks = 4 lines. `1 / 3` = start 0, span 2.
        let p = resolve_axis(LineRaw::Index(1), LineRaw::Index(3), 3, &no_area);
        assert_eq!((p.start, p.span), (Some(0), 2));
        // Negative: -1 is the last explicit line (line 4).
        let p = resolve_axis(LineRaw::Index(2), LineRaw::Index(-1), 3, &no_area);
        assert_eq!((p.start, p.span), (Some(1), 2));
        // span from a definite start.
        let p = resolve_axis(LineRaw::Index(2), LineRaw::Span(2), 3, &no_area);
        assert_eq!((p.start, p.span), (Some(1), 2));
        // auto + span rides the placement algorithm.
        let p = resolve_axis(LineRaw::Auto, LineRaw::Span(3), 3, &no_area);
        assert_eq!((p.start, p.span), (None, 3));
    }

    #[test]
    fn auto_placement_sparse_and_dense() {
        // 2 columns; items: A(span 2 cols), B(1), C(1): A fills row 0,
        // B and C pack row 1.
        let auto = AxisPlace {
            start: None,
            span: 1,
        };
        let span2 = AxisPlace {
            start: None,
            span: 2,
        };
        let items = vec![(span2, auto), (auto, auto), (auto, auto)];
        let placed = auto_place(items, 2, true, false);
        assert_eq!(placed[0].rows, 0..1);
        assert_eq!(placed[1].rows, 1..2);
        assert_eq!(placed[1].cols, 0..1);
        assert_eq!(placed[2].cols, 1..2);
        // Dense back-fills the hole a definite item leaves.
        let fixed_c2 = AxisPlace {
            start: Some(1),
            span: 1,
        };
        let items = vec![(fixed_c2, auto), (span2, auto), (auto, auto)];
        let placed = auto_place(items, 2, true, true);
        assert_eq!(placed[2].cols, 0..1);
        assert_eq!(
            placed[2].rows,
            0..1,
            "dense fills the gap before the wide item"
        );
    }
}
