//! Canonical engine-neutral TRust JavaScript host-boundary signatures.

pub(crate) const HOST_BOUNDARY_SIGNATURES: &[(&str, usize)] = &[
    ("__dom_create_element", 1),
    ("__dom_create_element_ns", 3),
    ("__dom_create_text", 1),
    ("__dom_create_fragment", 0),
    ("__dom_parse_document", 1),
    ("__dom_create_comment", 0),
    ("__dom_append", 2),
    ("__dom_insert_before", 3),
    ("__dom_detach", 1),
    ("__dom_owner_document", 1),
    ("__dom_adopt", 2),
    ("__dom_parent", 1),
    ("__dom_is_connected", 1),
    ("__dom_contains", 2),
    ("__dom_set_hover", 1),
    ("__dom_children", 1),
    ("__dom_slot_assigned", 1),
    ("__dom_assigned_slot", 1),
    ("__dom_next", 1),
    ("__dom_prev", 1),
    ("__dom_node_type", 1),
    ("__dom_tag", 1),
    ("__dom_namespace", 1),
    ("__dom_element_name", 1),
    ("__dom_get_attr", 2),
    ("__dom_computed", 2),
    ("__image_current_src", 1),
    ("__image_complete", 1),
    ("__match_media", 3),
    ("__dom_rect", 1),
    ("__dom_elements_from_point", 5),
    ("__dom_scroll_get", 2),
    ("__dom_scroll_set", 3),
    ("__dom_set_attr", 3),
    ("__dom_remove_attr", 2),
    ("__dom_attr_names", 1),
    ("__dom_text", 1),
    ("__dom_set_text", 2),
    ("__dom_inner_html", 1),
    ("__dom_set_inner_html", 2),
    ("__dom_load_frame", 3),
    ("__dom_outer_html", 1),
    ("__dom_insert_adjacent", 3),
    ("__dom_query", 3),
    ("__dom_matches", 2),
    ("__dom_get_by_id", 1),
    ("__dom_upgrade_candidates", 2),
    ("__dom_ce_candidates", 1),
    ("__dom_wrapper_subtree", 1),
    ("__dom_clone", 2),
    ("__dom_doc_element", 0),
    ("__html_dda", 0),
    ("__url_parse", 2),
    ("__url_set", 3),
    ("__dom_attach_shadow", 1),
    ("__dom_shadow_root", 1),
    ("__dom_adopt_styles", 2),
    ("__css_parse", 1),
    ("__css_supports_selector", 1),
    ("__dom_template_content", 1),
    ("__http_fetch", 5),
    ("__http_fetch_async", 5),
    ("__dom_run_injected_script", 1),
    ("__dom_run_classic_script", 3),
    ("__dom_allocate_job_context", 0),
    ("__dom_create_window_realm", 8),
    ("__dom_set_job_context", 1),
    ("__dom_release_job_context", 1),
    ("__dom_load_injected_stylesheet", 1),
    ("__cookie_get", 0),
    ("__cookie_set", 1),
    ("__clock_now", 0),
    ("__clock_set", 1),
    ("__storage_get", 2),
    ("__storage_set", 3),
    ("__storage_remove", 2),
    ("__storage_clear", 1),
    ("__storage_key", 2),
    ("__storage_len", 1),
    ("__blob_mirror", 3),
    ("__crypto_sha256_digest", 1),
    ("__compression_encode", 2),
    ("__text_encode", 1),
    ("__dom_popover", 2),
    ("__ws_open", 2),
    ("__ws_send", 3),
    ("__ws_close", 3),
    ("__worker_spawn", 4),
    ("__worker_post", 2),
    ("__worker_terminate", 1),
    ("__worker_self_post", 1),
    ("__worker_self_close", 0),
    ("__wasm_validate", 1),
    ("__wasm_compile", 1),
    ("__wasm_module_imports", 1),
    ("__wasm_module_exports", 1),
    ("__wasm_module_custom_sections", 2),
    ("__wasm_instantiate", 3),
    ("__wasm_instance_exports", 2),
    ("__wasm_call_export", 2),
    ("__wasm_global_new", 3),
    ("__wasm_global_get", 1),
    ("__wasm_global_set", 2),
    ("__wasm_memory_new", 2),
    ("__wasm_memory_size", 1),
    ("__wasm_memory_grow", 2),
    ("__wasm_memory_buffer", 1),
    ("__wasm_table_new", 4),
    ("__wasm_table_length", 1),
    ("__wasm_table_get", 2),
    ("__wasm_table_set", 3),
    ("__wasm_table_grow", 3),
];

/// Serialize a non-negative CSS pixel length with stable layout precision and
/// without non-canonical trailing zeroes.
pub(crate) fn serialize_css_px(value: f64) -> String {
    let mut number = format!("{:.4}", value.max(0.0));
    while number.ends_with('0') {
        number.pop();
    }
    if number.ends_with('.') {
        number.pop();
    }
    if number.is_empty() {
        number.push('0');
    }
    number.push_str("px");
    number
}
